baseurl: //jasmine.github.io
exclude:
  - _tmp
  - src
  - node_modules
  - vendor
  - Rakefile
  - LICENSE
  - README.md
  - Gemfile*
  - "*.json"

collections:
  archives:
    output: true
    permalink: archives/:path
  api:
    output: true
    permalink: api/:path
  browser-runner-api:
    output: true
    permalink: api/browser-runner/:path
  npm-api:
    output: true
    permalink: api/npm/:path
  tutorials:
    output: true
    permalink: tutorials/:path
  upgrade-guides:
    output: true
    permalink: upgrade-guides/:path
  faq:
    output: false

sass:
  sass_dir: css/_scss
  style: compressed

plugins:
  - jekyll-redirect-from
