baseurl: //jasmine.github.io
exclude:
  - _tmp
  - src
  - node_modules
  - vendor
  - Rakefile
  - LICENSE
  - README.md
  - Gemfile*
  - "*.json"

collections:
  versions:
    output: true
    permalink: :path
  api:
    output: true
    permalink: api/:path
  tutorials:
    output: true
    permalink: tutorials/:path
  faq:
    output: false

sass:
  sass_dir: css/_scss
  style: compressed

plugins:
  - jekyll-redirect-from
